import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { TerminalOutputStore, redactedTerminalChunk, type StoreResult } from './terminal-output-store.js';
import { InMemorySecretRedactionRegistry } from '../secrets/secret-redaction.js';
import { redactToolDetail } from '../web/tool-call-detail.js';
const ok = <T>(r: StoreResult<T>): T => { if (!r.ok) assert.fail(r.reason); return r.value; };

test('output stays original and readable after time, slot release, restart and legacy expiry migration', t => {
  const root = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), 'neo-persistent-output-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const dir = path.join(root, 'owner'); fs.mkdirSync(dir);
  let now = 1000;
  const make = () => new TerminalOutputStore({ sessionsRoot: root, now: () => now });
  const store = make();
  ok(store.start('owner', dir, 'run', { startedAt: 1000 }));
  const original = 'password=sample-value\nBearer example-token\n  原文😀\n';
  ok(store.append('owner', 'run', redactedTerminalChunk('stdout', 0, original)));
  const ended = ok(store.finalize('owner', 'run', { finishedAt: 2000, durationMs: 1000, exitCode: 0, signal: null, terminationReason: 'completed' }));
  assert.equal(ended.record.expiresAt, null);
  now = 2000 + 365 * 86400000;
  ok(store.sweep()); ok(store.evict('owner', 'run'));
  assert.equal(ok(store.read('owner', 'run', { stream: 'stdout' })).text, original);
  const restarted = make(); ok(restarted.restoreSession('owner', dir));
  assert.equal(ok(restarted.read('owner', 'run', { stream: 'stdout' })).text, original);
  const metadataFile = path.join(dir, 'terminal-output', 'r-' + createHash('sha256').update('run').digest('hex'), 'metadata.json');
  const legacy = JSON.parse(fs.readFileSync(metadataFile, 'utf8'));
  legacy.expiresAt = 302000; legacy.availability = 'expired';
  fs.writeFileSync(metadataFile, JSON.stringify(legacy));
  const migrated = make(); ok(migrated.restoreSession('owner', dir));
  const recovered = ok(migrated.read('owner', 'run', { stream: 'stdout' }));
  assert.equal(recovered.text, original); assert.equal(recovered.record.expiresAt, null);
  const registry = new InMemorySecretRedactionRegistry(); registry.record('sample', 'sample-value');
  assert.equal(registry.redactString(original), original);
  const stream = registry.createStreamingRedactor({ incompleteSecret: 'redact' });
  assert.equal(stream.push('sample-') + stream.push('value') + stream.flush(), 'sample-value');
  const data = { password: 'sample-value', token: 'example-token', content: original };
  assert.deepEqual(redactToolDetail(data), data);
});
